sudo: required
services:
    - docker

before_install:
    - docker build -t gpoppe329/docker-app -f Dockerfile.dev .

script: 
    - docker run -e CI=true gpoppe329/docker-app npm run test

deploy: 
    edge: true
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-app"
    env: "DockerApp-env"
    bucket_name: "elasticbeanstalk-us-east-1-644004268101"
    bucket_path: "docker-app"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

